name: CICD

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: ğŸ³ Login to Docker Hub
        env:
          DOCKER_PASSWORD: "Cloudnexus@1234"
        run: echo "Cloudnexus@1234" | docker login -u "cloudansh" --password-stdin

      - name:  Build Docker Image
        run: docker build -t cloudansh/react:latest .

      - name: ğŸš€ Push Docker Image to Docker Hub
        run: docker push cloudansh/react:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ³ Docker Login (Optional, only if your EC2 needs auth)
        env:
          DOCKER_PASSWORD: "Cloudnexus@1234"
        run: echo "Cloudnexus@1234" | docker login -u "cloudansh" --password-stdin

      - name: ğŸ“¥ Pull Image from Docker Hub
        run: docker pull cloudansh/react:latest

      - name: ğŸ—‘ï¸ Remove Old Container if exists
        run: docker rm -f fmssystem-container || true

      - name: ğŸš€ Run New Container
        run: docker run -d -p 3000:80 --name system-container cloudansh/react:latest
